remote_theme: pages-themes/cayman@v0.2.0

title: "PickMasters — Smart Pick-and-Place Robotic System"
description: "MEC 483: Mechatronics System Design — Abu Dhabi University, Spring 2026"

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
